task_id:"viNWxksbsGWNvjFIyiYck" situation_id:"JjGUroo5eX0H4_wuvIFet" check_item:{check_item_id:"2_nk4qYb1eBdNukdqJS90" command:{command_id:"RUURM8F2bAdkNNP4tE2tT" command_line:"progate diagnose"}} check_item:{check_item_id:"qwKadnj9s0lZWbHOrwLsg" command:{command_id:"kL2JKL-PW4A__3nm0jtnw" command_line:"npm run test"}}